[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.24"

evm_version = "cancun"
optimizer = true
optimizer_runs = 20_000

fs_permissions = [
    { access = "read-write", path = "./" },
    { access = "read-write", path = "../euler-interfaces" },
]
